import {
  User,
  UserRole,
  Project,
  ProjectMember,
  ProjectMemberRole,
  Issue,
  IssueStatus,
  IssueSeverity,
  IssuePriority,
  IssueSource,
  Comment,
  IssueHistory,
  Scan,
  ScanStatus,
  ScanFinding,
  ScanFindingStatus,
  NotificationItem,
} from "../types";

export const INITIAL_USERS: User[] = [
  {
    id: "u-101",
    name: "Alex River",
    email: "alex.river@fixora.io",
    role: UserRole.ADMIN,
    is_active: true,
    created_at: "2026-01-10T08:00:00Z",
  },
  {
    id: "u-102",
    name: "Sarah Chen",
    email: "sarah.chen@fixora.io",
    role: UserRole.USER,
    is_active: true,
    created_at: "2026-01-12T09:30:00Z",
  },
  {
    id: "u-103",
    name: "Liam Vance",
    email: "liam.vance@fixora.io",
    role: UserRole.USER,
    is_active: true,
    created_at: "2026-01-15T11:00:00Z",
  },
  {
    id: "u-104",
    name: "Maya Patel",
    email: "maya.patel@fixora.io",
    role: UserRole.USER,
    is_active: true,
    created_at: "2026-01-20T14:15:00Z",
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "p-fixora-core",
    name: "Fixora Core",
    key: "FIX",
    description: "Main issue tracking platform, API gateway, and Celery task orchestration backend.",
    github_repo_url: "https://github.com/Rohan-S-Mathad/Fixora",
    created_by: "u-101",
    created_at: "2026-01-10T10:00:00Z",
    updated_at: "2026-02-28T16:20:00Z",
    members_count: 4,
    issues_count: 14,
  },
  {
    id: "p-auth-service",
    name: "Security & Auth Service",
    key: "SEC",
    description: "OAuth2, JWT cookie rotation, RBAC permission engine, and audit logging microservice.",
    github_repo_url: "https://github.com/Rohan-S-Mathad/Fixora-Auth",
    created_by: "u-101",
    created_at: "2026-01-15T12:00:00Z",
    updated_at: "2026-02-27T10:15:00Z",
    members_count: 3,
    issues_count: 7,
  },
  {
    id: "p-scanner-worker",
    name: "Code Security Scanner",
    key: "SCAN",
    description: "Static AST analysis worker utilizing Semgrep, Bandit, Trivy and LLM deep inference.",
    github_repo_url: "https://github.com/Rohan-S-Mathad/Fixora-Scanner",
    created_by: "u-102",
    created_at: "2026-01-22T09:00:00Z",
    updated_at: "2026-02-29T08:45:00Z",
    members_count: 3,
    issues_count: 9,
  },
];

export const INITIAL_MEMBERS: ProjectMember[] = [
  {
    id: "pm-1",
    project_id: "p-fixora-core",
    user_id: "u-101",
    role: ProjectMemberRole.ADMIN,
    user: INITIAL_USERS[0],
    joined_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "pm-2",
    project_id: "p-fixora-core",
    user_id: "u-102",
    role: ProjectMemberRole.DEVELOPER,
    user: INITIAL_USERS[1],
    joined_at: "2026-01-12T10:00:00Z",
  },
  {
    id: "pm-3",
    project_id: "p-fixora-core",
    user_id: "u-103",
    role: ProjectMemberRole.DEVELOPER,
    user: INITIAL_USERS[2],
    joined_at: "2026-01-15T11:00:00Z",
  },
  {
    id: "pm-4",
    project_id: "p-fixora-core",
    user_id: "u-104",
    role: ProjectMemberRole.VIEWER,
    user: INITIAL_USERS[3],
    joined_at: "2026-01-20T14:15:00Z",
  },
];

export const INITIAL_ISSUES: Issue[] = [
  {
    id: "iss-101",
    project_id: "p-fixora-core",
    reporter_id: "u-101",
    issue_number: 101,
    title: "SQL Injection in issue search filter parameter 'search'",
    description: "Raw SQL concatenation observed when executing dynamic search filtering on issues endpoint without SQLAlchemy parameterized queries.",
    status: IssueStatus.IN_PROGRESS,
    severity: IssueSeverity.CRITICAL,
    priority: IssuePriority.URGENT,
    component: "Search & Database",
    assignee_id: "u-102",
    assignee: INITIAL_USERS[1],
    reporter: INITIAL_USERS[0],
    source: IssueSource.REPO_SCAN,
    scan_finding_id: "find-201",
    reproduction_steps: "1. Send GET /api/v1/projects/{id}/issues?search=' OR 1=1 --\n2. Observe unescaped raw query execution in PostgreSQL logs.",
    suggested_fix: "Use `filter(or_(Issue.title.ilike(f'%{query}%'), Issue.description.ilike(f'%{query}%')))` instead of raw string formatting in engine.execute().",
    labels: ["security", "sql-injection", "cve-candidate", "high-priority"],
    created_at: "2026-02-28T09:30:00Z",
    updated_at: "2026-02-29T10:15:00Z",
  },
  {
    id: "iss-102",
    project_id: "p-fixora-core",
    reporter_id: "u-103",
    issue_number: 102,
    title: "JWT refresh token cookie not properly invalidated on Safari / iOS",
    description: "Logout endpoint clears cookie with SameSite=Lax without domain header, causing stale refresh tokens to be transmitted on subdomains.",
    status: IssueStatus.OPEN,
    severity: IssueSeverity.HIGH,
    priority: IssuePriority.HIGH,
    component: "Authentication",
    assignee_id: "u-101",
    assignee: INITIAL_USERS[0],
    reporter: INITIAL_USERS[2],
    source: IssueSource.MANUAL,
    reproduction_steps: "1. Log in via iOS Safari.\n2. Click Logout.\n3. Verify /auth/refresh still succeeds due to browser cookie retention.",
    suggested_fix: "Set `max_age=0, expires=0, path='/', domain=settings.COOKIE_DOMAIN` on `response.delete_cookie()`.",
    labels: ["auth", "cookies", "safari", "security"],
    created_at: "2026-02-27T14:20:00Z",
    updated_at: "2026-02-28T11:00:00Z",
  },
  {
    id: "iss-103",
    project_id: "p-fixora-core",
    reporter_id: "u-102",
    issue_number: 103,
    title: "Celery repository scanner worker thread starvation under concurrent scans",
    description: "When 4+ repository scans trigger simultaneously, Celery pool exhausts GitHub API rate limit tokens without exponential backoff.",
    status: IssueStatus.IN_REVIEW,
    severity: IssueSeverity.HIGH,
    priority: IssuePriority.HIGH,
    component: "Scanner Worker",
    assignee_id: "u-103",
    assignee: INITIAL_USERS[2],
    reporter: INITIAL_USERS[1],
    source: IssueSource.AI_ASSISTANT,
    reproduction_steps: "Trigger 5 scan requests concurrently from the AI Bug Hunter interface.",
    suggested_fix: "Implement a token bucket rate limiter in `app/tasks/scanner.py` using Redis distributed lock.",
    labels: ["celery", "concurrency", "performance"],
    created_at: "2026-02-26T16:00:00Z",
    updated_at: "2026-02-29T09:40:00Z",
  },
  {
    id: "iss-104",
    project_id: "p-fixora-core",
    reporter_id: "u-101",
    issue_number: 104,
    title: "Hardcoded fallback JWT secret key in development configuration",
    description: "Bandit flagged a default fallback secret string `supersecretkey123` in settings when SECRET_KEY environment variable is absent.",
    status: IssueStatus.RESOLVED,
    severity: IssueSeverity.CRITICAL,
    priority: IssuePriority.URGENT,
    component: "Config & Security",
    assignee_id: "u-101",
    assignee: INITIAL_USERS[0],
    reporter: INITIAL_USERS[0],
    source: IssueSource.REPO_SCAN,
    scan_finding_id: "find-203",
    suggested_fix: "Enforce strict pydantic validation: raise ValueError if SECRET_KEY is not supplied in production environment.",
    labels: ["security", "secrets", "bandit"],
    created_at: "2026-02-25T11:00:00Z",
    updated_at: "2026-02-28T18:00:00Z",
  },
  {
    id: "iss-105",
    project_id: "p-fixora-core",
    reporter_id: "u-104",
    issue_number: 105,
    title: "Memory leak in SSE notification stream connection pool",
    description: "Client disconnects without cleanly unregistering the Redis pub/sub subscriber, causing memory usage to climb 200MB/day.",
    status: IssueStatus.OPEN,
    severity: IssueSeverity.MEDIUM,
    priority: IssuePriority.MEDIUM,
    component: "Notifications",
    assignee_id: "u-102",
    assignee: INITIAL_USERS[1],
    reporter: INITIAL_USERS[3],
    source: IssueSource.MANUAL,
    reproduction_steps: "Open and close browser tab 50 times while subscribed to /api/v1/notifications/stream.",
    suggested_fix: "Wrap SSE generator in `try...finally` block that calls `pubsub.unsubscribe()` and `pubsub.close()`.",
    labels: ["sse", "memory-leak", "backend"],
    created_at: "2026-02-27T10:00:00Z",
    updated_at: "2026-02-28T12:00:00Z",
  },
  {
    id: "iss-106",
    project_id: "p-fixora-core",
    reporter_id: "u-103",
    issue_number: 106,
    title: "pgvector embedding index cosine similarity query latency spike",
    description: "Vector similarity search on 50k+ bug descriptions slows down from 12ms to 450ms when IVFFlat index lists parameter is sub-optimal.",
    status: IssueStatus.IN_PROGRESS,
    severity: IssueSeverity.MEDIUM,
    priority: IssuePriority.MEDIUM,
    component: "AI & pgvector",
    assignee_id: "u-103",
    assignee: INITIAL_USERS[2],
    reporter: INITIAL_USERS[2],
    source: IssueSource.MANUAL,
    suggested_fix: "Re-index with HNSW (`USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)`).",
    labels: ["database", "pgvector", "performance"],
    created_at: "2026-02-28T15:30:00Z",
    updated_at: "2026-02-29T08:00:00Z",
  },
  {
    id: "iss-107",
    project_id: "p-fixora-core",
    reporter_id: "u-104",
    issue_number: 107,
    title: "Kanban board card drag state flicker on mobile Safari viewport",
    description: "Touch gesture triggers browser bounce effect simultaneously with card displacement.",
    status: IssueStatus.RESOLVED,
    severity: IssueSeverity.LOW,
    priority: IssuePriority.LOW,
    component: "Frontend UI",
    assignee_id: "u-102",
    assignee: INITIAL_USERS[1],
    reporter: INITIAL_USERS[3],
    source: IssueSource.MANUAL,
    suggested_fix: "Add `touch-action: none` and `overscroll-behavior: contain` to Kanban drag container elements.",
    labels: ["frontend", "mobile", "kanban"],
    created_at: "2026-02-24T13:00:00Z",
    updated_at: "2026-02-27T17:00:00Z",
  },
  {
    id: "iss-108",
    project_id: "p-fixora-core",
    reporter_id: "u-101",
    issue_number: 108,
    title: "Unbounded file upload size in attachment API causing HTTP 502",
    description: "Uploading crash logs greater than 10MB fails without informative client error.",
    status: IssueStatus.CLOSED,
    severity: IssueSeverity.LOW,
    priority: IssuePriority.LOW,
    component: "Attachments",
    assignee_id: "u-103",
    assignee: INITIAL_USERS[2],
    reporter: INITIAL_USERS[0],
    source: IssueSource.MANUAL,
    suggested_fix: "Add client-side size check and FastAPI `UploadFile` chunk-based size limiter.",
    labels: ["api", "uploads"],
    created_at: "2026-02-20T10:00:00Z",
    updated_at: "2026-02-25T16:00:00Z",
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: "c-1",
    issue_id: "iss-101",
    user_id: "u-101",
    user: INITIAL_USERS[0],
    content: "Identified during static code security scan. The vulnerability is in `app/services/issue.py` line 142.",
    is_ai_generated: false,
    created_at: "2026-02-28T09:40:00Z",
    updated_at: "2026-02-28T09:40:00Z",
  },
  {
    id: "c-2",
    issue_id: "iss-101",
    user_id: "u-102",
    user: INITIAL_USERS[1],
    content: "I've drafted a hotfix replacing the raw text concatenation with SQLAlchemy parameter binding. Testing against pgvector embeddings now.",
    is_ai_generated: false,
    created_at: "2026-02-28T14:10:00Z",
    updated_at: "2026-02-28T14:10:00Z",
  },
  {
    id: "c-3",
    issue_id: "iss-101",
    user_id: "u-101",
    user: INITIAL_USERS[0],
    content: "AI Analysis verification: Semgrep rule `python.lang.security.audit.raw-sql` will pass with the prepared statement approach.",
    is_ai_generated: true,
    created_at: "2026-02-28T15:00:00Z",
    updated_at: "2026-02-28T15:00:00Z",
  },
];

export const INITIAL_HISTORY: IssueHistory[] = [
  {
    id: "h-1",
    issue_id: "iss-101",
    user_id: "u-101",
    user: INITIAL_USERS[0],
    field_changed: "status",
    old_value: "open",
    new_value: "in_progress",
    created_at: "2026-02-28T10:00:00Z",
  },
  {
    id: "h-2",
    issue_id: "iss-101",
    user_id: "u-101",
    user: INITIAL_USERS[0],
    field_changed: "assignee",
    old_value: "Unassigned",
    new_value: "Sarah Chen",
    created_at: "2026-02-28T10:05:00Z",
  },
  {
    id: "h-3",
    issue_id: "iss-101",
    user_id: "u-102",
    user: INITIAL_USERS[1],
    field_changed: "priority",
    old_value: "high",
    new_value: "urgent",
    created_at: "2026-02-28T11:20:00Z",
  },
];

export const INITIAL_SCAN_FINDINGS: ScanFinding[] = [
  {
    id: "find-201",
    scan_id: "scan-901",
    tool: "semgrep",
    title: "SQL Injection in dynamic filter query",
    description: "User input from search query is formatted directly into a raw SQL clause without parameter sanitization.",
    file_path: "backend/app/services/issue.py",
    line_number: 142,
    code_snippet: "query = f\"SELECT * FROM issues WHERE title LIKE '%{search_term}%' AND project_id = '{project_id}'\"\nresults = db.execute(text(query)).fetchall()",
    severity: IssueSeverity.CRITICAL,
    confidence: "high",
    ai_analysis: "Critical SQL Injection vulnerability allows arbitrary SQL execution by an authenticated member. An attacker could craft a payload such as `' UNION SELECT id, email, hashed_password FROM users --` to dump database contents.",
    ai_suggested_fix: "stmt = select(Issue).where(\n    Issue.project_id == project_id,\n    Issue.title.ilike(f\"%{search_term}%\")\n)\nresults = db.scalars(stmt).all()",
    evidence: "Detected tainted variable `search_term` flowing from request query params directly into text formatted query string.",
    status: ScanFindingStatus.CREATED_ISSUE,
    created_issue_id: "iss-101",
    created_at: "2026-02-28T09:15:00Z",
  },
  {
    id: "find-202",
    scan_id: "scan-901",
    tool: "bandit",
    title: "Use of insecure cryptographic hashing (MD5)",
    description: "The MD5 hash function is cryptographically broken and should not be used for security-sensitive operations or token generation.",
    file_path: "backend/app/core/security.py",
    line_number: 88,
    code_snippet: "import hashlib\n\ndef generate_etag(payload: bytes) -> str:\n    return hashlib.md5(payload).hexdigest()",
    severity: IssueSeverity.HIGH,
    confidence: "high",
    ai_analysis: "MD5 is susceptible to collision attacks. While used here for ETag generation, best practice dictates using SHA-256 (or Blake2b) to prevent collision-based cache poisoning.",
    ai_suggested_fix: "import hashlib\n\ndef generate_etag(payload: bytes) -> str:\n    return hashlib.sha256(payload).hexdigest()",
    evidence: "B303: Blacklist call - use of insecure MD5 hash function.",
    status: ScanFindingStatus.PENDING,
    created_at: "2026-02-28T09:15:00Z",
  },
  {
    id: "find-203",
    scan_id: "scan-901",
    tool: "semgrep",
    title: "Hardcoded secret or development default credentials in config",
    description: "Default fallback secret string detected for JWT signing in configuration class.",
    file_path: "backend/app/config.py",
    line_number: 24,
    code_snippet: "class Settings(BaseSettings):\n    SECRET_KEY: str = \"dev_secret_key_change_in_production_123456789\"\n    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30",
    severity: IssueSeverity.CRITICAL,
    confidence: "high",
    ai_analysis: "Leaving a default static secret key in repository source code enables token forgery if an instance runs without properly mounted environment secrets.",
    ai_suggested_fix: "class Settings(BaseSettings):\n    SECRET_KEY: str  # Required without default in production\n    \n    @field_validator(\"SECRET_KEY\")\n    def validate_secret(cls, v):\n        if len(v) < 32:\n            raise ValueError(\"SECRET_KEY must be at least 32 characters long\")\n        return v",
    evidence: "Semgrep rule `generic.secrets.security.detected-hardcoded-secret` triggered.",
    status: ScanFindingStatus.CREATED_ISSUE,
    created_issue_id: "iss-104",
    created_at: "2026-02-28T09:15:00Z",
  },
  {
    id: "find-204",
    scan_id: "scan-901",
    tool: "ai_agent",
    title: "Missing authorization check on project member role modification",
    description: "Endpoint allows any project member to modify role permissions of other members, missing `admin` permission check.",
    file_path: "backend/app/router/projects.py",
    line_number: 95,
    code_snippet: "@router.put(\"/{project_id}/members/{user_id}\")\ndef update_member_role(project_id: UUID, user_id: UUID, role: str, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):\n    # Missing check: verify current_user is project admin\n    return project_service.update_member_role(db, project_id, user_id, role)",
    severity: IssueSeverity.HIGH,
    confidence: "medium",
    ai_analysis: "Horizontal Privilege Escalation: A standard viewer or developer member can promote themselves or another user to admin because role verification is omitted in the router handler.",
    ai_suggested_fix: "member = db.query(ProjectMember).filter(\n    ProjectMember.project_id == project_id,\n    ProjectMember.user_id == current_user.id\n).first()\nif not member or member.role != ProjectMemberRole.ADMIN.value:\n    raise HTTPException(status_code=403, detail=\"Only project admins can update member roles\")",
    evidence: "AI AST flow graph indicated absent permission decorator or role comparison before service dispatch.",
    status: ScanFindingStatus.PENDING,
    created_at: "2026-02-28T09:15:00Z",
  },
  {
    id: "find-205",
    scan_id: "scan-901",
    tool: "trivy",
    title: "Vulnerable dependency: FastAPI vulnerable to ReDoS in CORS middleware",
    description: "Installed package version contains known vulnerability CVE-2024-XXXX with regex parsing.",
    file_path: "backend/requirements.txt",
    line_number: 8,
    code_snippet: "fastapi==0.109.0\nuvicorn==0.27.0\npydantic==2.6.0",
    severity: IssueSeverity.MEDIUM,
    confidence: "high",
    ai_analysis: "FastAPI prior to 0.110.0 had a regular expression denial of service vulnerability when parsing wildcard origins in CORSMiddleware.",
    ai_suggested_fix: "fastapi>=0.115.0\nuvicorn>=0.30.0\npydantic>=2.8.0",
    evidence: "Trivy CVE scan match: GHSA-q6w7-q6w7-xxxx",
    status: ScanFindingStatus.PENDING,
    created_at: "2026-02-28T09:15:00Z",
  },
  {
    id: "find-206",
    scan_id: "scan-901",
    tool: "semgrep",
    title: "Unvalidated Redirect in GitHub OAuth callback handler",
    description: "The `redirect_uri` parameter is reflected from query parameter without whitelist validation.",
    file_path: "backend/app/router/auth.py",
    line_number: 112,
    code_snippet: "@router.get(\"/github/callback\")\ndef oauth_callback(code: str, redirect_to: str = \"/\"):\n    token = exchange_code(code)\n    return RedirectResponse(url=redirect_to)",
    severity: IssueSeverity.LOW,
    confidence: "medium",
    ai_analysis: "Open redirect vulnerability allows an attacker to construct a phishing link passing an external target URL like `redirect_to=https://evil.com`.",
    ai_suggested_fix: "if not redirect_to.startswith(\"/\") or \"//\" in redirect_to:\n    redirect_to = \"/dashboard\"",
    evidence: "Unsanitized URL redirected directly in HTTP 302 response.",
    status: ScanFindingStatus.DISMISSED,
    created_at: "2026-02-28T09:15:00Z",
  },
];

export const INITIAL_SCANS: Scan[] = [
  {
    id: "scan-901",
    project_id: "p-fixora-core",
    initiated_by: "u-101",
    scan_type: "repository",
    status: ScanStatus.COMPLETED,
    target_url: "https://github.com/Rohan-S-Mathad/Fixora",
    started_at: "2026-02-28T09:12:00Z",
    completed_at: "2026-02-28T09:15:24Z",
    created_at: "2026-02-28T09:12:00Z",
    summary: {
      total_findings: 6,
      critical: 2,
      high: 2,
      medium: 1,
      low: 1,
      security_score: "B-",
      scanned_files: 48,
      duration_ms: 3240,
    },
    findings: INITIAL_SCAN_FINDINGS,
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    user_id: "u-101",
    title: "Critical Issue Assigned",
    message: "You have been assigned to FIX-102: JWT refresh token cookie not properly invalidated.",
    type: "issue_assigned",
    read: false,
    link: "iss-102",
    created_at: "2026-02-28T14:25:00Z",
  },
  {
    id: "notif-2",
    user_id: "u-101",
    title: "Repository Scan Completed",
    message: "Fixora Core scan completed with 2 critical and 2 high security findings.",
    type: "scan_completed",
    read: false,
    link: "scan-901",
    created_at: "2026-02-28T09:16:00Z",
  },
  {
    id: "notif-3",
    user_id: "u-101",
    title: "New Comment on FIX-101",
    message: "Sarah Chen commented: 'I've drafted a hotfix replacing the raw text concatenation...'",
    type: "comment_added",
    read: true,
    link: "iss-101",
    created_at: "2026-02-28T14:12:00Z",
  },
];
